name: Build and deploy
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format

      - name: Build Storybook
        run: yarn build-storybook
        env:
          NODE_ENV: production

      - name: Semantic Release
        run: yarn semantic-release-publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy to GitHub page
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
